<a href="https://colab.research.google.com/github/yamazaki-riko/python_learning/blob/koshien_google-colab/koshien_bt_validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
import sqlite3
import pandas as pd
import numpy as np
from scipy.optimize import minimize

drive.mount('/content/drive')
conn = sqlite3.connect("/content/drive/MyDrive/koshien/koshien.db")
print("✅ DB接続完了")

Mounted at /content/drive
✅ DB接続完了

In [2]:
df_games = pd.read_sql("""
    SELECT year, winner_school, loser_school
    FROM tmp_tournament_games
    WHERE winner_score IS NOT NULL
""", conn)

print(f"試合数: {len(df_games)}試合")
display(df_games.head())

試合数: 207試合

   year winner_school loser_school
0  2022         国学院栃木         日大三島
1  2022            明豊           樹徳
2  2022          一関学院         京都国際
3  2022        八戸学院光星        愛工大名電
4  2022         愛工大名電           星稜

In [3]:
def calc_bradley_terry(df):
    teams = sorted(set(df["winner_school"]) | set(df["loser_school"]))
    idx   = {t: i for i, t in enumerate(teams)}
    n     = len(teams)

    def neg_log_likelihood(params):
        strength = np.exp(params)
        total = 0.0
        for _, row in df.iterrows():
            w = idx[row["winner_school"]]
            l = idx[row["loser_school"]]
            total -= np.log(strength[w] / (strength[w] + strength[l]))
        return total

    result = minimize(
        neg_log_likelihood,
        x0=np.zeros(n),
        method="L-BFGS-B"
    )

    strength = np.exp(result.x)
    df_result = pd.DataFrame({
        "school":   teams,
        "strength": strength
    }).sort_values("strength", ascending=False).reset_index(drop=True)
    df_result["rank"] = df_result.index + 1
    return df_result

print("✅ 関数の定義完了")

✅ 関数の定義完了

In [4]:
# 2022〜2023年のデータで強さを計算
df_train = df_games[df_games["year"] <= 2023]
df_bt    = calc_bradley_terry(df_train)

# 2024年の出場校を取得
df_2024 = pd.read_sql("""
    SELECT school_name, district
    FROM tmp_koshien_appearances_summer
    WHERE year = 2024
""", conn)

# BTモデルの結果と結合
df_pred = df_2024.merge(
    df_bt[["school", "strength", "rank"]],
    left_on  = "school_name",
    right_on = "school",
    how      = "left"
)

# 強さでソートしてポイントを割り当て
df_pred = df_pred.sort_values("strength", ascending=False).reset_index(drop=True)
df_pred["bt_rank"]   = df_pred.index + 1
df_pred["bt_points"] = range(49, 0, -1)

print("🏆 2024年 BTモデル予測ランキング（上位20校）")
display(df_pred[["bt_rank","school_name","district","bt_points"]].head(20))

🏆 2024年 BTモデル予測ランキング（上位20校）

    bt_rank school_name district  bt_points
0         1       愛工大名電       愛知         49
1         2        神村学園      鹿児島         48
2         3         富山商       富山         47
3         4        聖光学院       福島         46
4         5         花巻東       岩手         45
5         6        大阪桐蔭       大阪         44
6         7          広陵       広島         43
7         8        大垣日大       岐阜         42
8         9          北陸       福井         41
9        10         上田西       長野         40
10       11          興南       沖縄         39
11       12        創志学園       岡山         38
12       13          海星       長崎         37
13       14         鶴岡東       山形         36
14       15          明豊       大分         35
15       16          英明       香川         34
16       17         有田工       佐賀         33
17       18        明徳義塾       高知         32
18       19       智辯和歌山      和歌山         31
19       20        山梨学院       山梨         30

In [5]:
# 2024年の実際の勝利数を集計
df_2024_actual = pd.read_sql("""
    SELECT winner_school, COUNT(*) AS wins
    FROM tmp_tournament_games
    WHERE year = 2024
    GROUP BY winner_school
    ORDER BY wins DESC
""", conn)

print("2024年 実際の勝利数ランキング:")
display(df_2024_actual)

# BTモデルの予測と実際の勝利数を比較
df_compare = df_pred[["bt_rank","school_name","bt_points"]].merge(
    df_2024_actual,
    left_on  = "school_name",
    right_on = "winner_school",
    how      = "left"
).fillna({"wins": 0})

df_compare["wins"] = df_compare["wins"].astype(int)

print("\n📊 予測 vs 実際の比較:")
display(df_compare[["bt_rank","school_name","bt_points","wins"]])

2024年 実際の勝利数ランキング:

   winner_school  wins
0           京都国際     6
1           関東第一     4
2           青森山田     3
3           神村学園     3
4           早稲田実     3
5           滋賀学園     2
6          東海大相模     2
7          岡山学芸館     2
8           大阪桐蔭     2
9             大社     2
10          健大高崎     2
11         中京大中京     2
12           霞ヶ浦     1
13           金足農     1
14        西日本短大付     1
15            菰野     1
16          聖光学院     1
17            石橋     1
18           有田工     1
19          智弁学園     1
20          明徳義塾     1
21         新潟産大付     1
22           掛川西     1
23            広陵     1
24          岐阜城北     1
25          小松大谷     1
26           創成館     1

📊 予測 vs 実際の比較:

    bt_rank school_name  bt_points  wins
0         1       愛工大名電         49     0
1         2        神村学園         48     3
2         3         富山商         47     0
3         4        聖光学院         46     1
4         5         花巻東         45     0
5         6        大阪桐蔭         44     2
6         7          広陵         43     1
7         8        大垣日大         42     0
8         9          北陸         41     0
9        10         上田西         40     0
10       11          興南         39     0
11       12        創志学園         38     0
12       13          海星         37     0
13       14         鶴岡東         36     0
14       15          明豊         35     0
15       16          英明         34     0
16       17         有田工         33     1
17       18        明徳義塾         32     1
18       19       智辯和歌山         31     0
19       20        山梨学院         30     0
20       21        京都国際         29     6
21       22        白樺学園         28     0
22       23        札幌日大         27     0
23       24        青森山田         26     3
24       25         金足農         25     1
25       26        聖和学園         24     0
26       27         霞ケ浦         23     0
27       28          石橋         22     1
28       29        健大高崎         21     2
29       30        花咲徳栄         20     0
30       31       木更津総合         19     0
31       32         関東一         18     0
32       33       早稲田実業         17     0
33       34       東海大相模         16     2
34       35        新潟明訓         15     0
35       36        小松大谷         14     1
36       37         掛川西         13     1
37       38          菰野         12     1
38       39        滋賀学園         11     2
39       40        智辯学園         10     0
40       41        報徳学園          9     0
41       42        鳥取城北          8     0
42       43       石見智翠館          7     0
43       44         南陽工          6     0
44       45         帝京五          5     0
45       46         阿南光          4     0
46       47      西日本短大附          3     0
47       48         熊本工          2     0
48       49      聖心ウルスラ          1     0